# Generated by Django 2.2.5 on 2019-12-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_gitrepo_knownledgeof_studytimeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knownledgeof',
            name='framework_image',
        ),
    ]
