# Generated by Django 2.2.5 on 2019-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_knownledgeof_framework_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownledgeof',
            name='framework_image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
