# Generated by Django 2.2.5 on 2019-12-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20191206_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownledgeof',
            name='framework_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
