# Generated by Django 2.2.5 on 2019-12-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20191206_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownledgeof',
            name='framework_image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
