# Generated by Django 2.2.5 on 2019-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('description', models.CharField(max_length=264, unique=True)),
                ('link', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gitrepo',
        ),
    ]
